name: Ajv Schema Validation

on:
  pull_request:
  push:

jobs:
  schema-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
      # Ajv CLI v5 поддерживается на Node 16/18/20; выберем 20 для единообразия
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show versions
        run: |
          node -v
          npm -v
          npx -y ajv-cli@5 --version

      - name: Validate JSON Schemas (report -> insight/hypothesis)
        run: |
          # ВАЖНО: без -c/--code, без -c true
          # Подключаем ссылочные схемы через -r, валидируем sample
          npx -y ajv-cli@5 validate \
            --spec=draft2020 \
            --strict=false \
            --allowUnionTypes \
            -s spec/schemas/report.schema.json \
            -r spec/schemas/insight.schema.json \
            -r spec/schemas/hypothesis.schema.json \
            -d spec/samples/report.valid.json
