name: Ajv Schema Validation

on:
  push:
  pull_request:

jobs:
  schema-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ajv CLI
        run: npm i -g ajv-cli@5

      - name: Versions
        run: |
          node -v
          npm -v
          ajv --version

      - name: Validate JSON Schemas (report -> insight/hypothesis)
        run: |
          ajv validate \
            -s spec/schemas/report.schema.json \
            -r spec/schemas/insight.schema.json \
            -r spec/schemas/hypothesis.schema.json \
            -d spec/samples/report.valid.json \
            --spec=draft2020 --strict=false
