name: Ajv Schema Validation

on:
  push:
  pull_request:

jobs:
  schema-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show versions and files
        run: |
          node -v
          npm -v
          ls -la spec/schemas
          ls -la spec/samples

      - name: Validate JSON Schemas + sample
        run: |
          npx --yes ajv-cli@5 validate \
            --spec=draft2020 --strict=false --allowUnionTypes --all-errors \
            -s spec/schemas/report.schema.json \
            -r spec/schemas/insight.schema.json \
            -r spec/schemas/hypothesis.schema.json \
            -d spec/samples/report.valid.json
