# .github/workflows/ci.yml
name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: backend   # tests import app.* from backend/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r backend/requirements.txt
      - run: pip install pytest ruff mypy httpx
      - run: python -m compileall backend
      - name: Ruff (non-blocking)
        run: ruff check backend || true
      - name: MyPy (non-blocking)
        run: mypy --ignore-missing-imports backend || true
      - name: Pytest
        run: pytest -q
