name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # опционально: статика/тайпчекеры, если есть в requirements
          pip install ruff mypy || true

      - name: Ruff (non-blocking)
        continue-on-error: true
        run: ruff check .

      - name: Mypy (non-blocking)
        continue-on-error: true
        run: mypy || true

      - name: Pytest
        run: pytest -q
