# .github/workflows/ci.yml 
  api:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system libs for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf-2.0-0 \
            libffi-dev \
            shared-mime-info \
            fonts-liberation
      - run: python -m pip install --upgrade pip
      - run: pip install -r backend/requirements.txt
      - run: pip install pytest ruff mypy httpx
      - run: python -m compileall backend
      - run: ruff check backend || true
      - run: mypy --ignore-missing-imports backend || true
      - run: pytest -q
