name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: backend   # <— главное: тесты видят пакет app из backend/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r backend/requirements.txt
      - run: pip install pytest ruff mypy httpx
      - run: python -m compileall backend

      # Линтеры пока «мягкие» — не ломают билд на предупреждениях
      - name: Ruff (non-blocking)
        run: ruff check backend || true
      - name: Mypy (non-blocking)
        run: mypy --ignore-missing-imports backend || true

      - name: Pytest
        run: pytest -q
